joy_node:
  auto_repeat_rate: 30
  coalesce_interval: 0.0333
  deadzone: 0.01

raspicam_node:
  camera_frame_id: raspicam
  camera_id: 0
  camera_info_url: package://raspicam_node/camera_info/camerav1_1280x720.yaml
  camera_name: camerav1_1280x720
  enable_raw: false
  exposure_mode: antishake
  framerate: 90 # high frame-rate to reduce motion blur
  height: 120
  width: 160
  ISO: 800

servos:
  pwm_frequency: 50
  throttle:
    channel: 0
    center: 320
    direction: 1
    range: 100
  steering:
    channel: 1
    center: 325
    direction: 1
    range: 180

teleop:
  drive:
    type: topic
    message_type: geometry_msgs/TwistStamped
    topic_name: donkey/drive
    axis_mappings:
      - axis: 1
        target: twist.linear.x
        scale: 1.0
      - axis: 3
        target: twist.angular.z
        scale: 1.0
